# Server links which are sent to players in the options menu.
# Component supports minimessage.
# Order is as shown in list menu. (Lower number higher up)
links:
  - component: "<rainbow>made you look lol</rainbow>"
    uri: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
    order: 0

# Server resource packs which are applied on join.
# URI is a direct link to a zip file.
# Hash is the resourcepack hash, if empty will be downloaded and calculated.
# Priority determines pack order, higher priority will put the pack higher up in the list.
resource-packs:
  - uri: "https://github.com/CloudieSMP/resourcepack-s10/releases/latest/download/cloudie-s10-RP.zip"
    hash: ""
    priority: 100

tpa:
  # Time in seconds before a tpa request expires.
  request-expire-time: 60
    # Time in seconds before the player gets tped.
  tpa-delay: 2
home:
  max-homes: 5