name: System
description: Cloudie SMP S10 System
api-version: "1.21.11"
authors: [Sebiann]
website: https://sebiann.moe

version: ${version}
main: System
load: STARTUP

dependencies:
  server:
    LuckPerms:
      required: false

default-permission: false
permissions:
  cloudie.silent:
    description: Allows the player to use the /system command.
    children:
        cloudie.silent.join: true
        cloudie.silent.leave: true